In [4]:
import torch
import numpy as np

In [7]:
t = torch.Tensor()
type(t)

torch.Tensor

# Tensor attributes

In [8]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


tensor computations depend on the device and type.

# Creation options using data

In [24]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [25]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [26]:
torch.tensor(data)

tensor([1, 2, 3])

In [27]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [30]:
torch.from_numpy(data)

tensor([1, 2, 3])

# Creation options without data

In [32]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [34]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [35]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
torch.rand(2,2)

tensor([[0.9461, 0.4444],
        [0.7972, 0.1496]])

# Creating PyTorch Tensors-Best Options
Constructor: torch.Tensor()
factories: torch.tensor() torch.as_tensor() torch.from_numpy()
## sharing memory for performance 
sharing data: torch.as_tensor() torch.from_tensor()
copying data:torch.Tensor() torch.tensor()

The best option is torch.tensor()

# Tensor operation types
1. Reshaping opetations
2. Element-wise operations
3. Reduction operations
4. Access operations

## Reshaping opetions 


two ways to get tensor's shape

In [48]:
import torch
t = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
],dtype = torch.float32)

In [49]:
t.shape

torch.Size([3, 4])

In [50]:
t.size()

torch.Size([3, 4])

In [51]:
len(t.shape) #get tensor's rank

2

In [52]:
t.numel() #get number of element

12

reshape tensor

In [53]:
t.reshape(1,12)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [54]:
t.reshape(2,6)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [56]:
t.reshape(1,12).squeeze() #squeezing a tensor removes all axes of length one.

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

# CNN Flatten Oparetion 
flatten a tensor means remove all of axes exept 1.
tensor's flatten oparetion is common oparetion.
传递给全连接层的卷积层输出必须在进入全连接层之前进行flatten

In [57]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [58]:
flatten(t)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [59]:
import torch

In [60]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

In [61]:
t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

In [62]:
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [65]:
t = torch.stack((t1,t2,t3))
t.size()

torch.Size([3, 4, 4])

In [66]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

We see them as 4x4 pictures.
flatten tensors

In [68]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

# Element-wise tensor operation

In [69]:
import torch
import numpy as np

In [70]:
t1 = torch.tensor([
    [1,2],
    [3,4]
],dtype = torch.float32)

In [71]:
t2 = torch.tensor([
    [9,8],
    [7,6]
],dtype = torch.float32)

Two tensors must have same shape in order to perform an element opetation.

In [74]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [75]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [76]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [77]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [78]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

**Scalar tensor is been broadcast the shape of tensor 1,and then element operation performed**

In [82]:
t1 = torch.tensor([
    [1,1],
    [2,2]
],dtype = torch.float32)

In [83]:
t2 = torch.tensor([3,3],dtype = torch.float32)

In [84]:
t1 + t2 

tensor([[4., 4.],
        [5., 5.]])

## Comparison Operation

In [85]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
],dtype = torch.float32)

In [86]:
t.eq(0) #==

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [87]:
t.ge(0) #>=

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [88]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [89]:
t.le(0) #<=

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [90]:
t.lt(0) #<

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [91]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [92]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [93]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

# Argmax and reduction operation
A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor.
argmax is a math function which told us index location of the maximun value in a tensor.

In [94]:
import torch
import numpy as np

In [95]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
],dtype = torch.float32)

In [96]:
t.max()

tensor(5.)

In [97]:
t.argmax()

tensor(11)

In [99]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [100]:
t.max(dim = 0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [101]:
t.argmax(dim = 0)

tensor([2, 1, 1, 2])

In [103]:
t.max(dim = 1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [105]:
t.argmax(dim = 1)

tensor([3, 1, 3])